"""add date fields

Revision ID: 038fcbbce94f
Revises: e2489887e541
Create Date: 2018-05-08 11:32:35.814751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '038fcbbce94f'
down_revision = 'e2489887e541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flat', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('flat', sa.Column('date_updated', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_flat_url'), 'flat', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flat_url'), table_name='flat')
    op.drop_column('flat', 'date_updated')
    op.drop_column('flat', 'date_created')
    # ### end Alembic commands ###
