"""add url

Revision ID: 1bf4cfe5f50e
Revises: 810d12df8e12
Create Date: 2018-04-19 14:51:21.802197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bf4cfe5f50e'
down_revision = '810d12df8e12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flat', sa.Column('url', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_flat_url'), 'flat', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flat_url'), table_name='flat')
    op.drop_column('flat', 'url')
    # ### end Alembic commands ###
