"""add flat

Revision ID: 4b27de21e72a
Revises: 
Create Date: 2018-04-16 12:07:12.635710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b27de21e72a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(precision=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flat_district'), 'flat', ['district'], unique=False)
    op.create_index(op.f('ix_flat_name'), 'flat', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flat_name'), table_name='flat')
    op.drop_index(op.f('ix_flat_district'), table_name='flat')
    op.drop_table('flat')
    # ### end Alembic commands ###
