"""add area

Revision ID: 6ca1777ef8cf
Revises: b3254547e2c8
Create Date: 2018-04-18 15:36:06.723982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ca1777ef8cf'
down_revision = 'b3254547e2c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flat', sa.Column('area', sa.Float(precision=2), nullable=True))
    op.create_index(op.f('ix_flat_area'), 'flat', ['area'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flat_area'), table_name='flat')
    op.drop_column('flat', 'area')
    # ### end Alembic commands ###
