"""temporary remove name uniqe

Revision ID: b3254547e2c8
Revises: 4b27de21e72a
Create Date: 2018-04-16 13:25:53.449063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3254547e2c8'
down_revision = '4b27de21e72a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_flat_name', table_name='flat')
    op.create_index(op.f('ix_flat_name'), 'flat', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flat_name'), table_name='flat')
    op.create_index('ix_flat_name', 'flat', ['name'], unique=1)
    # ### end Alembic commands ###
