"""add url to flat

Revision ID: e2489887e541
Revises: 1bf4cfe5f50e
Create Date: 2018-05-01 17:22:15.337936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2489887e541'
down_revision = '1bf4cfe5f50e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_flat_url', table_name='flat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_flat_url', 'flat', ['url'], unique=1)
    # ### end Alembic commands ###
